name: ProgressionPlus
version: '1.0-SNAPSHOT'
main: com.lukecywon.progressionPlus.ProgressionPlus
api-version: '1.21'
commands:
  artifact:
    description: Main command for artifact items
    usage: /artifact <subcommand>
    permission: progressionplus.artifact
    permission-message: You do not have permission to use this.

  fixme:
    description: Fix player invulnerability

  wormhole:
    description: Wormhole teleport command
    usage: /wormhole <accept|reject>
  cooldown:
    description: Manage item cooldowns
    usage: /cooldown clear <player>
    permission: progressionplus.artifact
    permission-message: You do not have permission.
  addsouls:
    description: Adds souls to the Void Reaper
    usage: /addsouls [amount]
    permission: progressionplus.artifact
    permission-message: You do not have permission to use this command.
  trade:
    description: Accept or reject a trade request
    usage: /trade <accept|reject>